/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TaaSProductBirth } from "./TaaSProductBirth";
export * as factories from "./factories";
export { TaaSProductBirth__factory } from "./factories/TaaSProductBirth__factory";
