/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TaaSProductBirth {
  export type ProductBirthStruct = {
    gpid: string;
    brand: string;
    model: string;
    category: string;
    factory: string;
    batch: string;
    createdAt: BigNumberish;
    creator: AddressLike;
    fingerprint: BytesLike;
  };

  export type ProductBirthStructOutput = [
    gpid: string,
    brand: string,
    model: string,
    category: string,
    factory: string,
    batch: string,
    createdAt: bigint,
    creator: string,
    fingerprint: string
  ] & {
    gpid: string;
    brand: string;
    model: string;
    category: string;
    factory: string;
    batch: string;
    createdAt: bigint;
    creator: string;
    fingerprint: string;
  };
}

export interface TaaSProductBirthInterface extends Interface {
  getFunction(nameOrSignature: "birthProduct" | "getProduct"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProductBorn"): EventFragment;

  encodeFunctionData(
    functionFragment: "birthProduct",
    values: [string, string, string, string, string, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getProduct", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "birthProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
}

export namespace ProductBornEvent {
  export type InputTuple = [
    gpid: string,
    brand: string,
    model: string,
    creator: AddressLike
  ];
  export type OutputTuple = [
    gpid: string,
    brand: string,
    model: string,
    creator: string
  ];
  export interface OutputObject {
    gpid: string;
    brand: string;
    model: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaaSProductBirth extends BaseContract {
  connect(runner?: ContractRunner | null): TaaSProductBirth;
  waitForDeployment(): Promise<this>;

  interface: TaaSProductBirthInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  birthProduct: TypedContractMethod<
    [
      _gpid: string,
      _brand: string,
      _model: string,
      _category: string,
      _factory: string,
      _batch: string,
      _fingerprint: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getProduct: TypedContractMethod<
    [_gpid: string],
    [TaaSProductBirth.ProductBirthStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "birthProduct"
  ): TypedContractMethod<
    [
      _gpid: string,
      _brand: string,
      _model: string,
      _category: string,
      _factory: string,
      _batch: string,
      _fingerprint: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [_gpid: string],
    [TaaSProductBirth.ProductBirthStructOutput],
    "view"
  >;

  getEvent(
    key: "ProductBorn"
  ): TypedContractEvent<
    ProductBornEvent.InputTuple,
    ProductBornEvent.OutputTuple,
    ProductBornEvent.OutputObject
  >;

  filters: {
    "ProductBorn(string,string,string,address)": TypedContractEvent<
      ProductBornEvent.InputTuple,
      ProductBornEvent.OutputTuple,
      ProductBornEvent.OutputObject
    >;
    ProductBorn: TypedContractEvent<
      ProductBornEvent.InputTuple,
      ProductBornEvent.OutputTuple,
      ProductBornEvent.OutputObject
    >;
  };
}
