/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TaaSProductBirthInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "assignOwner"
      | "birthProduct"
      | "clearStolen"
      | "exists"
      | "getCore"
      | "getMeta"
      | "getState"
      | "markStolen"
      | "owner"
      | "stolen"
      | "transferOwner"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assignOwner",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "birthProduct",
    values: [string, string, string, string, string, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "clearStolen", values: [string]): string;
  encodeFunctionData(functionFragment: "exists", values: [string]): string;
  encodeFunctionData(functionFragment: "getCore", values: [string]): string;
  encodeFunctionData(functionFragment: "getMeta", values: [string]): string;
  encodeFunctionData(functionFragment: "getState", values: [string]): string;
  encodeFunctionData(functionFragment: "markStolen", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values: [string]): string;
  encodeFunctionData(functionFragment: "stolen", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwner",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assignOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "birthProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearStolen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMeta", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markStolen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stolen", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwner",
    data: BytesLike
  ): Result;
}

export interface TaaSProductBirth extends BaseContract {
  connect(runner?: ContractRunner | null): TaaSProductBirth;
  waitForDeployment(): Promise<this>;

  interface: TaaSProductBirthInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  assignOwner: TypedContractMethod<
    [gpid: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  birthProduct: TypedContractMethod<
    [
      gpid: string,
      brand: string,
      model: string,
      category: string,
      factory: string,
      batch: string,
      hash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  clearStolen: TypedContractMethod<[gpid: string], [void], "nonpayable">;

  exists: TypedContractMethod<[arg0: string], [boolean], "view">;

  getCore: TypedContractMethod<
    [gpid: string],
    [[string, string, string, string, string, string]],
    "view"
  >;

  getMeta: TypedContractMethod<
    [gpid: string],
    [[bigint, string, string]],
    "view"
  >;

  getState: TypedContractMethod<[gpid: string], [[string, boolean]], "view">;

  markStolen: TypedContractMethod<[gpid: string], [void], "nonpayable">;

  owner: TypedContractMethod<[arg0: string], [string], "view">;

  stolen: TypedContractMethod<[arg0: string], [boolean], "view">;

  transferOwner: TypedContractMethod<
    [gpid: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assignOwner"
  ): TypedContractMethod<
    [gpid: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "birthProduct"
  ): TypedContractMethod<
    [
      gpid: string,
      brand: string,
      model: string,
      category: string,
      factory: string,
      batch: string,
      hash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "clearStolen"
  ): TypedContractMethod<[gpid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCore"
  ): TypedContractMethod<
    [gpid: string],
    [[string, string, string, string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMeta"
  ): TypedContractMethod<[gpid: string], [[bigint, string, string]], "view">;
  getFunction(
    nameOrSignature: "getState"
  ): TypedContractMethod<[gpid: string], [[string, boolean]], "view">;
  getFunction(
    nameOrSignature: "markStolen"
  ): TypedContractMethod<[gpid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "stolen"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwner"
  ): TypedContractMethod<
    [gpid: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
